output_root: 'hpatches/cvpr_model'
postfix: 'PoSFeat'
load_path: ./ckpts/CVPR_model/modules

loss_distance: 'cos'
output_desc: True
output_img: True

data: 'HPatch_SIFT' # the images in megadepth_caps have been resized to 640x480, therefore, we don't need to resize the images 
data_config_extract:
    data_path: '/home/kunbpc/data/kunb/hpatches/hpatches-sequences-release'
    prune_kp: True
    num_pts: 5000
    batch_size: 1
    workers: 4

use_sift: False

model_config: 
  backbone_config:
      encoder: 'resnet50'
      pretrained: True
      coarse_out_ch: 128
      fine_out_ch: 128
  localheader_config:
      in_channels: 192 # 128 for localmap 64 for localmap_small
      act: 'Softplus'
  align_local_grad: False
  local_input_elements: ['local_map', 'local_map_small']
  local_with_img: True
no_cuda: ['name1', 'name2']

detector: 'generate_kpts_single'
detector_config:
    num_pts: 8192
    stable: True
    use_nms: True # softnms, True, False
    nms_radius: 1
    thr: 0.9 # False or a float
    thr_mod: abs # max mean abs